# Site Settings
title:               RockTa!!
tagline:             게임 프로그래밍 일기
description:
baseurl:            #"/sdchihi"
url:                #"https://sdchihi.github.io/"
github:
  url:               #"https://github.com/sdchihi"
author:
  name:              "Shin DongChan"
  email:             "sdchihi@naver.com"
  github:            "sdchihi"
  facebook:          "sdchihi"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact
- title: GameProgramming
  url: /GameProgramming
- title: ETC
  url: /ETC

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
