# Site Settings
title:               RockTa!!
tagline:             동찬이의 게임 일기
description:
baseurl:            #"/sdchihi"
url:                #"https://sdchihi.github.io/"
github:             
  url:               #"https://github.com/sdchihi"
author:
  name:              "Shin DongChan"
  email:             "sdchihi@naver.com"
  github:            "sdchihi"
  facebook:          "sdchihi"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
